#!/bin/bash

ALPHA_FILES=/home/yjq/Downloads

PWD=`pwd | tr "/" " " | awk '{print $NF}'`

if [ $PWD != "pkgs" ] ; then
	echo "Error: this script must be run from the parsec-2.1/pkgs directory"
	exit
fi

tar zxf $ALPHA_FILES/parsec-2.1-extra-alpha-packages.tar.gz

echo "Unpacking configuration files"
tar zxf $ALPHA_FILES/parsec_m5_alpha_config_files.tar.gz
pushd parsec_m5_alpha_config_files >& /dev/null
cp parsec.conf ../../../config/.
cp alpha-gcc-hooks.bldconf ../../../config/.
cp gcc.bldconf ../../../config/.
cp -r inputproto/parsec ../../libs/inputproto/.
cp -r jpeg/parsec ../../libs/jpeg/.
cp -r kbproto/parsec ../../libs/kbproto/.
cp -r libX11/parsec ../../libs/libX11/.
cp -r libXau/parsec ../../libs/libXau/.
cp -r libXext/parsec ../../libs/libXext/.
cp -r libXmu/parsec ../../libs/libXmu/.
cp -r libpthreadstubs/parsec ../../libs/libpthreadstubs/.
cp -r libxcb/parsec ../../libs/libxcb/.
cp -r xcbproto/parsec ../../tools/xcbproto/.
cp -r xextproto/parsec ../../libs/xextproto/.
cp -r xproto/parsec ../../libs/xproto/.
cp -r xtrans/parsec ../../libs/xtrans/.
cp    libtool/parsec/alpha-gcc-hooks.bldconf ../../tools/libtool/parsec/alpha-gcc-hooks.bldconf
cp    gsl/parsec/alpha-gcc-hooks.bldconf ../../libs/gsl/parsec/alpha-gcc-hooks.bldconf
cp    x264/parsec/alpha-gcc-hooks.bldconf ../../apps/x264/parsec/alpha-gcc-hooks.bldconf
cp    imagick/parsec/alpha-gcc-hooks.bldconf ../../libs/imagick/parsec/alpha-gcc-hooks.bldconf
cp    glib/parsec/alpha-gcc-hooks.bldconf ../../libs/glib/parsec/alpha-gcc-hooks.bldconf
cp    glib/parsec/alpha.cache ../../libs/glib/parsec/alpha.cache
cp    glib/parsec/alpha.cache ../../libs/glib/parsec/alpha.cache.backup
cp    libxml2/parsec/alpha-gcc-hooks.bldconf ../../libs/libxml2/parsec/alpha-gcc-hooks.bldconf
cp    vips/parsec/alpha-gcc-hooks.bldconf ../../apps/vips/parsec/alpha-gcc-hooks.bldconf
cp    cmake/parsec/alpha-gcc-hooks.bldconf ../../tools/cmake/parsec/alpha-gcc-hooks.bldconf
cp    mesa/parsec/alpha-gcc-hooks.bldconf ../../libs/mesa/parsec/alpha-gcc-hooks.bldconf
cp    mesa/parsec/gcc.bldconf ../../libs/mesa/parsec/gcc.bldconf
cp    raytrace/parsec/alpha-gcc-hooks.bldconf ../../apps/raytrace/parsec/alpha-gcc-hooks.bldconf
cp    raytrace/parsec/gcc-pthreads.bldconf ../../apps/raytrace/parsec/gcc-pthreads.bldconf
cp    bodytrack/parsec/alpha-gcc-hooks.bldconf ../../apps/bodytrack/parsec/alpha-gcc-hooks.bldconf
cp    ssl/parsec/alpha-gcc-hooks.bldconf ../../libs/ssl/parsec/alpha-gcc-hooks.bldconf
cp    ssl/parsec/gcc.bldconf ../../libs/ssl/parsec/gcc.bldconf
cp    ferret/parsec/alpha-gcc-hooks.bldconf ../../apps/ferret/parsec/alpha-gcc-hooks.bldconf
cp    freqmine/parsec/alpha-gcc-hooks.bldconf ../../apps/freqmine/parsec/alpha-gcc-hooks.bldconf
cp    hooks/src/alpha_m5.S ../../libs/hooks/src/alpha_m5.S
cp    hooks/parsec/alpha-gcc-hooks.bldconf ../../libs/hooks/parsec/alpha-gcc-hooks.bldconf
cp    dedup/parsec/alpha-gcc-hooks.bldconf ../../kernels/dedup/parsec/alpha-gcc-hooks.bldconf
cp    zlib/parsec/alpha-gcc-hooks.bldconf ../../libs/zlib/parsec/alpha-gcc-hooks.bldconf
cp    yasm/parsec/alpha-gcc-hooks.bldconf ../../tools/yasm/parsec/alpha-gcc-hooks.bldconf

